### PR TITLE
upgrade to latest sagemaker-experiments

### PR DESCRIPTION
**Pull request by danabens**
upgrade to latest sagemaker-experiments

### CODE REVIEW

**Comment by danabens** [comment]
failure appears unrelated
```

test/integration/sagemaker/test_distributed_operations.py:85: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.6/dist-packages/sagemaker/estimator.py:236: in fit
    self.latest_training_job.wait(logs=logs)
/usr/local/lib/python3.6/dist-packages/sagemaker/estimator.py:605: in wait
    self.sagemaker_session.logs_for_job(self.job_name, wait=True)
/usr/local/lib/python3.6/dist-packages/sagemaker/session.py:1232: in logs_for_job
    self._check_job_status(job_name, description, 'TrainingJobStatus')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sagemaker.session.Session object at 0x7ff3dba21438>
job = 'sagemaker-test-2020-02-12-21-14-51-392'
desc = {'AlgorithmSpecification': {'TrainingImage': '142577830533.dkr.ecr.us-west-2.amazonaws.com/sagemaker-test:1.4.0-gpu-py... 52, 89000, tzinfo=tzlocal()), 'EnableInterContainerTrafficEncryption': False, 'EnableManagedSpotTraining': False, ...}
status_key_name = 'TrainingJobStatus'

    def _check_job_status(self, job, desc, status_key_name):
        """Check to see if the job completed successfully and, if not, construct and
        raise a ValueError.
    
        Args:
            job (str): The name of the job to check.
            desc (dict[str, str]): The result of ``describe_training_job()``.
            status_key_name (str): Status key name to check for.
    
        Raises:
            ValueError: If the training job fails.
        """
        status = desc[status_key_name]
        # If the status is capital case, then convert it to Camel case
        status = _STATUS_CODE_TABLE.get(status, status)
    
        if status != 'Completed' and status != 'Stopped':
            reason = desc.get('FailureReason', '(No reason provided)')
            job_type = status_key_name.replace('JobStatus', ' job')
>           raise ValueError('Error for {} {}: {} Reason: {}'.format(job_type, job, status, reason))
E           ValueError: Error for Training job sagemaker-test-2020-02-12-21-14-51-392: Failed Reason: CapacityError: Unable to provision requested ML compute capacity. Please retry using a different ML instance type.

/usr/local/lib/python3.6/dist-packages/sagemaker/session.py:928: ValueError
----------------------------- Captured stdout call -----------------------------
2020-02-12 21:14:52 Starting - Starting the training job...
2020-02-12 21:14:53 Starting - Launching requested ML instances...
2020-02-12 21:15:50 Starting - Insufficient capacity error from EC2 while launching instances, retrying!...
2020-02-12 21:16:20 Failed - Training job failed
..
----------------------------- Captured stderr call -----------------------------
WARNING:sagemaker:No framework_version specified, defaulting to version 0.4.
------------------------------ Captured log call -------------------------------
estimator.py                74 WARNING  No framework_version specified, defaulting to version 0.4.
============== 1 failed, 10 passed, 3 skipped in 3516.42 seconds ===============
```

**Comment by YYStreet** [comment]
> ### AWS CodeBuild CI Report
> * Result: FAILED
> * [Build Logs](https://f79laypnxd.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=f550221a-755a-4a41-a82b-da747954aa6b%2Fbuild.log) (available for 30 days)
> 
> _Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)_

Failure might because of the syntax error from newly added code of this PR.

```
[Container] 2020/03/02 17:32:41 Running command tox -e flake8
GLOB sdist-make: /codebuild/output/src330218452/src/github.com/aws/sagemaker-pytorch-container/setup.py
flake8 create: /codebuild/output/src330218452/src/github.com/aws/sagemaker-pytorch-container/.tox/flake8
flake8 installdeps: flake8, flake8-future-import
flake8 inst: /codebuild/output/src330218452/src/github.com/aws/sagemaker-pytorch-container/.tox/.tmp/package/1/sagemaker_pytorch_training-1.2.1.dev0.zip
flake8 installed: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support,bcrypt==3.1.7,boto3==1.12.11,botocore==1.15.11,cffi==1.14.0,Click==7.0,configparser==4.0.2,cryptography==2.8,docutils==0.15.2,entrypoints==0.3,enum34==1.1.9,flake8==3.7.9,flake8-future-import==0.4.6,Flask==1.1.1,functools32==3.2.3.post2,futures==3.3.0,gevent==1.4.0,greenlet==0.4.15,gunicorn==19.10.0,inotify-simple==1.2.1,ipaddress==1.0.23,itsdangerous==1.1.0,Jinja2==2.11.1,jmespath==0.9.5,MarkupSafe==1.1.1,mccabe==0.6.1,numpy==1.16.6,paramiko==2.4.2,protobuf==3.11.3,psutil==5.4.8,pyasn1==0.4.8,pycodestyle==2.5.0,pycparser==2.19,pyflakes==2.1.1,PyNaCl==1.3.0,python-dateutil==2.8.1,retrying==1.3.3,s3transfer==0.3.3,sagemaker-containers==2.8.1,sagemaker-pytorch-training==1.2.1.dev0,scipy==1.2.3,six==1.14.0,typing==3.7.4.1,urllib3==1.25.8,Werkzeug==0.15.5
flake8 run-test-pre: PYTHONHASHSEED='136166017'
flake8 runtests: commands[0] | flake8
./test/integration/sagemaker/test_experiments.py:25:72: E999 SyntaxError: invalid syntax
ERROR: InvocationError for command '/codebuild/output/src330218452/src/github.com/aws/sagemaker-pytorch-container/.tox/flake8/bin/flake8' (exited with code 1)
```

**Comment by YYStreet** [comment]
https://github.com/pytorch/vision/issues/1938

**Comment by codewithsk** [comment]
Hi Dana! Looks like the test is failing due to a missing pytest fixture:

```
  @pytest.mark.skip_py2_containers
  def test_training(sagemaker_session, ecr_image, instance_type, instance_count):
E       fixture 'instance_count' not found
```

**Comment by codewithsk** [comment]
@danabens Build is failing with the following error:

```
E       TypeError: load() got an unexpected keyword argument 'sagemaker_boto_name'
```

**Pull request merged**
